# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


import tkinter as tk
import subprocess
import sys
from tkinter import Canvas, Entry, Text, Button, PhotoImage, Scrollbar, Frame
from pathlib import Path
from datasets import load_dataset

# Load the TinyStories dataset
dataset = load_dataset("roneneldan/TinyStories")

# Define the get_story_excerpts function
def get_story_excerpts(dataset, num_stories=9):
    excerpts = []
    for i in range(min(num_stories, len(dataset['train']))):
        story = dataset['train'][i]['text']
        # Use the first sentence or first 100 characters as an excerpt
        excerpt = story.split('.')[0] + '.' if '.' in story else story[:100] + '...'
        excerpts.append((i, excerpt))
    return excerpts


# Function to open ReadingSession.py and pass the story to it
def show_story(story_text):
    subprocess.Popen([sys.executable, "ReadingSession.py", story_text])

# Paths
OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"assets\\frame4")

def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)

# Create the main application window
root = tk.Tk()
root.geometry("934x575")
root.configure(bg="#FFFFFF")
root.title("Read App")

canvas = Canvas(
    root,
    bg="#FFFFFF",
    height=575,
    width=934,
    bd=0,
    highlightthickness=0,
    relief="ridge"
)

canvas.place(x=0, y=0)
canvas.create_rectangle(
    0.0,
    0.0,
    934.0,
    582.0,
    fill="#D9D9D9",
    outline=""
)

image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    467.0,
    320.0,
    image=image_image_1
)

canvas.create_rectangle(
    0.0,
    0.0,
    934.0,
    64.0,
    fill="#F8F7F2",
    outline=""
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    466.0,
    32.0,
    image=image_image_2
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=885.0,
    y=9.0,
    width=48.0,
    height=48.0
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="flat"
)
button_2.place(
    x=0.0,
    y=5.0,
    width=48.0,
    height=48.0
)


#instruction
canvas.create_text(
    440.0,
    92.0,
    anchor="center",
    text="Select a story",
    fill="#000000",
    font=("Inter Medium", 40 * -1)
)

# Get excerpts to display as choices
excerpts = get_story_excerpts(dataset)

# Number of columns for grid layout
columns = 3

for i, (index, excerpt) in enumerate(excerpts):
    # Create a frame for each story block
    frame = tk.Frame(root, relief=tk.RAISED, borderwidth=3)
    frame.place(x=(i%columns)*320 + 10, y=(i//columns)*150 + 130)

    # Add a label with the story excerpt
    label = tk.Label(frame, text=f"Story {index + 1}: {excerpt}", wraplength=200)
    label.pack(padx=10, pady=10)

    # Add a button to read the story
    button = tk.Button(frame, text="Read Story", 
                       command=lambda i=index: show_story(dataset['train'][i]['text']))
    button.pack(padx=10, pady=10)

root.mainloop()